[package]
name = "trustify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
trustify-api = { path = "../graph" }
trustify-common = { path = "../common"}

actix = "0.13"
actix-web = "4"
anyhow = "1.0.72"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11.0"
log = "0.4.19"
packageurl = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.68", features = ["raw_value"] }
thiserror = "1"
utoipa = { version = "4", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "4", features = ["actix-web"] }
tokio = "1"
url = "2.5.0"
serde_urlencoded = "0.7.1"
reqwest = { version = "0.11.24", features = ["blocking"] }

oxide-auth = { version = "0.5.0" }
oxide-auth-actix = { version = "0.2.1" }

[dev-dependencies]
url-escape = "0.1.1"
