[package]
name = "trustify-integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
trustify-auth = { workspace = true }
trustify-common = { workspace = true }
trustify-infrastructure = { workspace = true }
trustify-entity = { workspace = true }
trustify-module-fetch = { workspace = true }
trustify-module-ingestor = { workspace = true }
trustify-module-importer = { workspace = true }
trustify-module-storage = { workspace = true }

anyhow = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
rust-lzma = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
test-context = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
